import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { generateLocators } from '../src/locators/generator.js';
import { createEmptyRegistry, type Registry, type RegistryEntry } from '../src/registry/schema.js';

function entry(component: string, overrides: Partial<RegistryEntry> = {}): RegistryEntry {
  return {
    component,
    tag: 'button',
    element_type: 'native_button',
    fingerprint: 'button|text=Send',
    semantic: {
      formcontrolname: null,
      aria_label: null,
      placeholder: null,
      text_content: 'Send',
      type: 'submit'
    },
    first_seen_version: 1,
    last_seen_version: 1,
    ...overrides
  };
}

describe('generateLocators mode', () => {
  let dir = '';
  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), 'testid-locator-mode-'));
  });
  afterEach(async () => {
    await fs.rm(dir, { recursive: true, force: true });
  });

  async function seed(registry: Registry): Promise<string> {
    await generateLocators(registry, { outDir: dir, mode: 'overwrite' });
    // Use the first component's file as the shared target in tests.
    const firstFile = path.join(dir, 'login.py');
    return firstFile;
  }

  const simpleRegistry: Registry = {
    ...createEmptyRegistry(1, '2026-04-20T10:00:00Z'),
    entries: {
      'login__button--send': entry('src/app/login/login.component.html')
    }
  };

  it('merge is the default when no mode or overwrite is given', async () => {
    const file = await seed(simpleRegistry);
    await fs.appendFile(file, '\nmy_custom = "xpath://custom"\n', 'utf8');
    await generateLocators(simpleRegistry, { outDir: dir });
    const contents = await fs.readFile(file, 'utf8');
    expect(contents).toContain('my_custom');
  });

  it('mode: overwrite discards prior content', async () => {
    const file = await seed(simpleRegistry);
    await fs.appendFile(file, '\nmy_custom = "xpath://custom"\n', 'utf8');
    await generateLocators(simpleRegistry, { outDir: dir, mode: 'overwrite' });
    const contents = await fs.readFile(file, 'utf8');
    expect(contents).not.toContain('my_custom');
  });

  it('mode: refuse fails when the file already exists', async () => {
    await seed(simpleRegistry);
    await expect(
      generateLocators(simpleRegistry, { outDir: dir, mode: 'refuse' })
    ).rejects.toThrow(/Refusing to overwrite/);
  });

  it('legacy overwrite: true maps to mode: overwrite', async () => {
    const file = await seed(simpleRegistry);
    await fs.appendFile(file, '\nmy_custom = "xpath://custom"\n', 'utf8');
    await generateLocators(simpleRegistry, { outDir: dir, overwrite: true });
    const contents = await fs.readFile(file, 'utf8');
    expect(contents).not.toContain('my_custom');
  });

  it('legacy overwrite: false maps to mode: refuse', async () => {
    await seed(simpleRegistry);
    await expect(
      generateLocators(simpleRegistry, { outDir: dir, overwrite: false })
    ).rejects.toThrow(/Refusing to overwrite/);
  });

  it('explicit mode wins over legacy overwrite', async () => {
    const file = await seed(simpleRegistry);
    await fs.appendFile(file, '\nmy_custom = "xpath://custom"\n', 'utf8');
    // Conflicting flags: mode says merge, overwrite says overwrite. mode wins.
    await generateLocators(simpleRegistry, { outDir: dir, mode: 'merge', overwrite: true });
    const contents = await fs.readFile(file, 'utf8');
    expect(contents).toContain('my_custom');
  });

  it('merge falls back to a fresh write when the target file does not exist', async () => {
    // Note: no seed() call - the target file doesn't exist yet.
    const result = await generateLocators(simpleRegistry, { outDir: dir, mode: 'merge' });
    expect(result.writtenPaths).toHaveLength(1);
    const contents = await fs.readFile(result.writtenPaths[0]!, 'utf8');
    expect(contents).toContain('# Generated by testid-gen-locators');
  });
});
