import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { loadLocatorSnapshot } from '../src/migrate/snapshot.js';
import { buildMigrationPlan } from '../src/migrate/plan.js';
import { applyRenames } from '../src/migrate/applier.js';
import { scanRobotProject, filterHitsByVariables } from '../src/migrate/scanner.js';
import { renderMigrationReport } from '../src/migrate/report.js';

const PY_HEADER = '# Generated by testid-gen-locators - do not edit.\n# Component: order\n\n';

async function writeLocatorFile(dir: string, name: string, lines: string[]): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, name), PY_HEADER + lines.join('\n') + '\n', 'utf8');
}

describe('migrate end-to-end', () => {
  let root = '';
  beforeEach(async () => {
    root = await fs.mkdtemp(path.join(os.tmpdir(), 'testid-mig-'));
  });
  afterEach(async () => {
    await fs.rm(root, { recursive: true, force: true });
  });

  it('renames variable references in robot files (dry-run leaves files untouched)', async () => {
    const oldDir = path.join(root, 'old');
    const newDir = path.join(root, 'new');
    const robotDir = path.join(root, 'tests');

    await writeLocatorFile(oldDir, 'order.py', [
      `orderButton = "xpath://*[@data-testid='order__button--save']"  # testid-managed`
    ]);
    await writeLocatorFile(newDir, 'order.py', [
      `orderButtons = "xpath://*[@data-testid='order__button--save']"  # testid-managed`
    ]);

    await fs.mkdir(robotDir, { recursive: true });
    const robotFile = path.join(robotDir, 'checkout.robot');
    const original = [
      '*** Settings ***',
      'Library  SeleniumLibrary',
      '',
      '*** Test Cases ***',
      'Save order',
      '    Click Element  ${orderButton}',
      '    Page Should Contain  ${orderButton}',
      ''
    ].join('\n');
    await fs.writeFile(robotFile, original, 'utf8');

    const [oldSnap, newSnap] = await Promise.all([
      loadLocatorSnapshot(oldDir),
      loadLocatorSnapshot(newDir)
    ]);
    const plan = buildMigrationPlan(oldSnap, newSnap);
    expect(plan.renames).toEqual([
      { testid: 'order__button--save', oldVariable: 'orderButton', newVariable: 'orderButtons' }
    ]);

    const renamesMap = new Map(plan.renames.map((r) => [r.oldVariable, r.newVariable]));
    const dry = await applyRenames({ robotDir, renames: renamesMap, dryRun: true });
    expect(dry.filesChanged).toBe(1);
    expect(dry.occurrencesChanged).toBe(2);
    expect(await fs.readFile(robotFile, 'utf8')).toBe(original);

    const live = await applyRenames({ robotDir, renames: renamesMap, dryRun: false });
    expect(live.filesChanged).toBe(1);
    expect(live.occurrencesChanged).toBe(2);
    const after = await fs.readFile(robotFile, 'utf8');
    expect(after).toContain('${orderButtons}');
    expect(after).not.toContain('${orderButton}');
  });

  it('does not touch references whose name is a substring of a renamed one', async () => {
    const oldDir = path.join(root, 'old');
    const newDir = path.join(root, 'new');
    const robotDir = path.join(root, 'tests');

    await writeLocatorFile(oldDir, 'order.py', [
      `order = "xpath://*[@data-testid='ord__btn']"  # testid-managed`
    ]);
    await writeLocatorFile(newDir, 'order.py', [
      `orderForm = "xpath://*[@data-testid='ord__btn']"  # testid-managed`
    ]);

    await fs.mkdir(robotDir, { recursive: true });
    const robotFile = path.join(robotDir, 'overlap.robot');
    await fs.writeFile(
      robotFile,
      '${order}\n${order_button}\n${orderly}\n${ordering}\n',
      'utf8'
    );

    const renamesMap = new Map([['order', 'orderForm']]);
    await applyRenames({ robotDir, renames: renamesMap, dryRun: false });
    const after = await fs.readFile(robotFile, 'utf8');
    expect(after).toBe('${orderForm}\n${order_button}\n${orderly}\n${ordering}\n');
  });

  it('reports orphan references that linger in robot files after a testid disappears', async () => {
    const oldDir = path.join(root, 'old');
    const newDir = path.join(root, 'new');
    const robotDir = path.join(root, 'tests');

    await writeLocatorFile(oldDir, 'legacy.py', [
      `legacyDropdown = "xpath://*[@data-testid='legacy__dropdown--type']"  # testid-managed`
    ]);
    await writeLocatorFile(newDir, 'legacy.py', []);

    await fs.mkdir(robotDir, { recursive: true });
    const robotFile = path.join(robotDir, 'old-spec.robot');
    await fs.writeFile(robotFile, '${legacyDropdown}\n', 'utf8');

    const [oldSnap, newSnap] = await Promise.all([
      loadLocatorSnapshot(oldDir),
      loadLocatorSnapshot(newDir)
    ]);
    const plan = buildMigrationPlan(oldSnap, newSnap);
    expect(plan.orphans).toHaveLength(1);

    const allHits = await scanRobotProject(robotDir);
    const orphanHits = filterHitsByVariables(
      allHits,
      new Set(plan.orphans.map((o) => o.oldVariable))
    );
    expect(orphanHits).toHaveLength(1);

    const text = renderMigrationReport({
      plan,
      hits: [],
      orphanHits,
      filesChanged: 0,
      occurrencesChanged: 0,
      dryRun: true,
      robotDir
    });
    expect(text).toContain('Orphans');
    expect(text).toContain('STILL REFERENCED');
  });

  it('only walks .robot and .resource files', async () => {
    const robotDir = path.join(root, 'tests');
    await fs.mkdir(robotDir, { recursive: true });
    await fs.writeFile(path.join(robotDir, 'a.robot'), '${foo}\n', 'utf8');
    await fs.writeFile(path.join(robotDir, 'b.resource'), '${foo}\n', 'utf8');
    await fs.writeFile(path.join(robotDir, 'c.txt'), '${foo}\n', 'utf8');
    await fs.writeFile(path.join(robotDir, 'd.py'), '${foo}\n', 'utf8');

    const renamesMap = new Map([['foo', 'bar']]);
    const result = await applyRenames({ robotDir, renames: renamesMap, dryRun: false });
    expect(result.filesChanged).toBe(2);
    expect(await fs.readFile(path.join(robotDir, 'a.robot'), 'utf8')).toBe('${bar}\n');
    expect(await fs.readFile(path.join(robotDir, 'b.resource'), 'utf8')).toBe('${bar}\n');
    expect(await fs.readFile(path.join(robotDir, 'c.txt'), 'utf8')).toBe('${foo}\n');
    expect(await fs.readFile(path.join(robotDir, 'd.py'), 'utf8')).toBe('${foo}\n');
  });
});
