import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { loadLocatorSnapshot } from '../src/migrate/snapshot.js';

const PY_HEADER = '# Generated by testid-gen-locators - do not edit.\n# Component: example\n\n';

describe('loadLocatorSnapshot', () => {
  let dir = '';
  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), 'testid-snap-'));
  });
  afterEach(async () => {
    await fs.rm(dir, { recursive: true, force: true });
  });

  it('returns empty maps when the dir does not exist', async () => {
    const snap = await loadLocatorSnapshot(path.join(dir, 'missing'));
    expect(snap.byTestid.size).toBe(0);
    expect(snap.byVariable.size).toBe(0);
    expect(snap.sourceFiles).toHaveLength(0);
  });

  it('parses managed lines into both maps', async () => {
    await fs.writeFile(
      path.join(dir, 'order.py'),
      PY_HEADER +
        `orderListThId = "xpath://*[@data-testid='order-list__th--id']"  # testid-managed\n` +
        `orderButton = "xpath://*[@data-testid='order__button--save']"  # testid-managed\n`,
      'utf8'
    );
    const snap = await loadLocatorSnapshot(dir);
    expect(snap.byTestid.get('order-list__th--id')).toBe('orderListThId');
    expect(snap.byTestid.get('order__button--save')).toBe('orderButton');
    expect(snap.byVariable.get('orderButton')).toBe('order__button--save');
    expect(snap.sourceFiles).toHaveLength(1);
  });

  it('ignores manual lines that lack the testid-managed marker', async () => {
    await fs.writeFile(
      path.join(dir, 'mixed.py'),
      PY_HEADER +
        `orderButton = "xpath://*[@data-testid='order__button--save']"  # testid-managed\n` +
        `myCustomLocator = "xpath://*[@id='custom']"\n` +
        `# orderButtonOld = "xpath://*[@data-testid='gone']"  # testid-managed\n`,
      'utf8'
    );
    const snap = await loadLocatorSnapshot(dir);
    expect(snap.byVariable.has('myCustomLocator')).toBe(false);
    expect(snap.byVariable.has('orderButtonOld')).toBe(false);
    expect(snap.byVariable.has('orderButton')).toBe(true);
  });

  it('handles a custom attribute name like data-cy', async () => {
    await fs.writeFile(
      path.join(dir, 'cypress.py'),
      PY_HEADER +
        `loginButton = "//*[@data-cy='login__button--send']"  # testid-managed\n`,
      'utf8'
    );
    const snap = await loadLocatorSnapshot(dir);
    expect(snap.byTestid.get('login__button--send')).toBe('loginButton');
  });

  it('walks subdirectories', async () => {
    await fs.mkdir(path.join(dir, 'apps/foo'), { recursive: true });
    await fs.writeFile(
      path.join(dir, 'apps/foo/page.py'),
      PY_HEADER +
        `fooButton = "xpath://*[@data-testid='foo__button--ok']"  # testid-managed\n`,
      'utf8'
    );
    const snap = await loadLocatorSnapshot(dir);
    expect(snap.byVariable.has('fooButton')).toBe(true);
  });
});
