/**
 * Pure rendering functions for the Robot Framework locator generator.
 *
 * These helpers take *already-resolved* data (testid strings, component names)
 * and produce Python source code. Keeping them pure makes the generator easy
 * to snapshot-test and keeps the I/O out of the transformation logic.
 */

import type { LocatorEntry, LocatorModule } from './types.js';

/**
 * Convert a testid segment like `order-list__table--auftragsliste` into a
 * full-path camelCase identifier: `orderListTableAuftragsliste`.
 *
 * The rules are intentionally permissive: any run of non-alphanumeric chars
 * acts as a word boundary, so `__` and `--` and stray underscores all work.
 * A leading digit would be illegal in Python — we prepend `tid` in that case.
 */
export function camelCaseTestid(testid: string): string {
  const parts = testid
    .split(/[^a-zA-Z0-9]+/)
    .filter((p) => p.length > 0)
    .map((p) => p.toLowerCase());
  if (parts.length === 0) return 'tid';
  const [first, ...rest] = parts;
  const joined =
    first! +
    rest
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join('');
  return /^[0-9]/.test(joined) ? `tid${joined.charAt(0).toUpperCase()}${joined.slice(1)}` : joined;
}

/** Convert a kebab component name into a snake_case Python filename stem. */
export function filenameForComponent(component: string): string {
  const stem = component.replace(/-/g, '_').replace(/[^a-zA-Z0-9_]/g, '_');
  return `${stem}.py`;
}

/** Build an XPath locator string for a testid. */
export function xpathFor(
  testid: string,
  attributeName: string,
  xpathPrefix: string
): string {
  const xpath = `//*[@${attributeName}='${testid}']`;
  return `${xpathPrefix}${xpath}`;
}

/**
 * Render one Python module to a string. The output looks like:
 *
 *     # Generated by testid-gen-locators — do not edit.
 *     # Component: order-list
 *     # Run testid-gen-locators after regenerating the registry.
 *
 *     orderListThId = "xpath://*[@data-testid='order-list__th--id']"  # testid-managed
 *     orderListThKunde = "xpath://*[@data-testid='order-list__th--kunde']"  # testid-managed
 *
 * The `# testid-managed` marker is what the existing Python replacer looks
 * for — emitted files drop straight into the rename workflow.
 */
export function renderLocatorModule(mod: LocatorModule): string {
  const lines: string[] = [];
  lines.push('# Generated by testid-gen-locators — do not edit.');
  lines.push(`# Component: ${mod.component}`);
  lines.push('# Re-run testid-gen-locators after every tagger run that changes the registry.');
  lines.push('');
  for (const entry of mod.entries) {
    lines.push(`${entry.variable} = "${entry.selector}"  # testid-managed`);
  }
  lines.push('');
  return lines.join('\n');
}

export function buildLocatorEntry(
  testid: string,
  attributeName: string,
  xpathPrefix: string
): LocatorEntry {
  return {
    variable: camelCaseTestid(testid),
    selector: xpathFor(testid, attributeName, xpathPrefix),
    testid
  };
}
